### ISSUE TITLE
Sidebar-Widget mit Bild, ohne padding?

### ISSUE THREAD

**Issue by marians** [kre8tiv/urwahl3000#14]
Ich hätte gerne die Möglichkeit, ein Bild in der Infospalte anzuzeigen, aber ohne Rand zum Widget.

So sieht das aktuell aus:

![image](https://user-images.githubusercontent.com/273727/37993620-7724afc0-320f-11e8-9c88-85617226cd03.png)

Ich habe versucht, folgenden CSS-Code hinzuzufügen:

```css
.widget.widget_media_image {padding: 0;}
```

Damit erhalte ich dieses Ergebnis:

![image](https://user-images.githubusercontent.com/273727/37993661-99b046ee-320f-11e8-980e-37c59b44b7a1.png)

Die paar Pixel Abstand unten werde ich aus irgend einem Grund aber leider nicht los.

@modulbuero Irgend eine Idee, was ich tun kann?

**Comment by kre8tiv** [comment]
Mit dem Plugin "image Widget" lassen sich Bilder ohne Rand einfügen (siehe auch http://kre8tiv.de/doku/urwahl3000/#plugins <http://kre8tiv.de/doku/urwahl3000/#plugins>).

**Comment by marians** [comment]
Danke, hat funktioniert.
