### ISSUE TITLE
Dashboard-Widget zu Neuigkeiten von kre8tiv

### ISSUE THREAD

**Issue by larsschellhas** [kre8tiv/urwahl3000#18]
Auf dem Dashboard wurden bisher die neuesten Posts von der kre8tiv-Webseite angezeigt.
Dort findet sich nun nur noch ein Hello-World-Post. Insofern kann das Widget auch entfernt werden, denke ich.

**Comment by modulbuero** [comment]
Habe den Feed auf die Github-Commits gewechselt, damit haben wir nun auch eine Versionshistorie im Dashboard. Außerdem sind die Links zur Doku usw. korrigiert. Danke für den Hinweis.

**Comment by larsschellhas** [comment]
Immer gerne ;) 
Danke fürs schnelle korrigieren!

**Comment by larsschellhas** [comment]
Ich glaube, da muss noch ein kleine Fix rein :)
Der Feed wird irgendwie nur 1-zeilig, bzw. ohne Zeilenumbruch dargestellt. Das liegt wohl am verwendeten <pre>-Tag. <p> dürfte sich zur Darstellung vermutlich besser eignen.

![image](https://user-images.githubusercontent.com/14281234/40192414-915f28e4-5a04-11e8-850c-726c0e1a6e7b.png)

**Comment by larsschellhas** [comment]
Der Pull-Request fixt zumindest den Überlauf des Texts. Allerdings konnte ich den doppelten Titel nicht entfernen. Bin mir nicht ganz sicher, woran das liegt.

**Comment by modulbuero** [comment]
Merged. Der doppelte Titel liegt im RSS-Feed von Github, denke ich. Kann ich aber für den Moment mit leben.
