### ISSUE TITLE
Kompatibel zu Wordpress 5.0 Gutenberg

### ISSUE THREAD

**Issue by a1880** [kre8tiv/urwahl3000#25]
Ist urwahl3000 kompatibel zur angekündigten Wordpress Version 5.0 "Gutenberg"?

Gruß und vielen Dank für urwahl3000!

Axel Kemper

**Comment by modulbuero** [comment]
Hallo Axel,

wir gehen im Moment nach unseren Tests davon aus, allerdings ändert sich auch konstant noch einiges an Gutenberg. Falls Probleme auftreten, melde dich gern direkt bei uns unter cj@modulbuero.de. 

Viele Grüße,
Christian
