### ISSUE TITLE
Links in Kopfzeile in der Mobilansicht nicht sichtbar 

### ISSUE THREAD

**Issue by svenkaemper** [kre8tiv/urwahl3000#26]
Die Navigation in der Kopfzeile (dunkelgrüner Balken am oberen Bildschirmrand) wird in der Mobilansicht bis auf die Suchfunktion komplett ausgeblendet – was schade ist, denn dort sind ja i.d.R. recht nützliche/wichtige Links untergebracht (in unserem Fall "Presse", "Kontakt" und "Mitglied werden"). Gibt es eine Möglichkeit, die Links der Kopfzeile auch mobil sicht- und nutzbar zu machen?

**Comment by modulbuero** [comment]
Hallo Sven,

prinzipiell geht das natürlich, du müsstest in deinem Child-Theme die Definitionen für `#portal` von der bisherigen Auflösungsgrenze `@media only screen and (min-width: 770px), all` befreien. Allerdings wird das dann in mobilen Auflösungen oben auch schnell eng, sprich man müsste von horizontalem auf vertikales Nebeneinander brechen – womit es dann schnell sehr hoch werden kann. Aber wenn du Ideen hast, wie's gut funktionieren würde, sind wir dafür gern offen.

Viele Grüße,
Christian

**Comment by dasaweb** [comment]
Hi, hängt vielleicht damit zusammen: Das Hamburger-Menü und die Suche funktionieren in der mobilen Ansicht nicht, d.h. das Seitenmenu ist nicht erreichbar.

**Comment by modulbuero** [comment]
@dasaweb habe das Issue getrennt und dir in #46 geantwortet.
