### ISSUE TITLE
Give option to deactivate kal3000

### ISSUE THREAD

**Issue by gumby-man** [kre8tiv/urwahl3000#27]
Hello,

nice move to include an event calendar, but there are other addons for this purpose, often with more functionality (venue lists for example). So now I see two menu entries in backend for the same purpose. I can hide one using another addon ("Admin Menu Editor"...) but that's not the way it should be.

Can you implement a way to remove kal3000 integration within child theme? Or give a customize option for this?

Regards

**Comment by modulbuero** [comment]
Hey,

absolutely, that's a good idea. Done in v2.1.16 as referenced above.

Best,
Christian
