### ISSUE TITLE
Schlagwortwolke mit Gewichtung

### ISSUE THREAD

**Issue by Harry-von-Borstel** [kre8tiv/urwahl3000#30]
Normalerweise hat die Schlagwortwolke in Wordpress eine angezeigte Gewichtung: Häufige Schlagwörter werden größer angezeigt, als weniger häufige.

In Urwahl3000 ist eine Gleichmacherei derart implementiert, dass alle Schlagwörter auf einheitliche Größe gezwungen werden. Ursache ist Zeile 686 in style.css, dort die Angabe `font-size: 0.9em!important;`.

Das `!important` verhindert das Überschreiben im Child-Theme, so dass ich keine andere Möglichkeit sah, als style.css lokal direkt zu ändern, um uns die Wolke schön zu machen (siehe z.B. http://www.gruene-wandsbek.de/gruenschnack/tag/fahrrad-stadt-hamburg/). Folge: Die Änderung geht bei jedem Update flöten.

Es wäre schön, wenn Urwahl3000 eine Schlagwortwolke mit Gewichtung ohne Hacks ermöglichen könnte.

Schöne Grüße aus Hamburg und vielen Dank für Euer Engagement für dieses großartige Projekt!

_Harry_

**Comment by modulbuero** [comment]
Hallo Harry,

guter Punkt, nehme ich sofort raus und veröffentliche ein Update.

Viele Grüße aus Siegen,
Christian

**Comment by modulbuero** [comment]
Das würde ich einfach mal so hier stehen lassen, damit andere sich dran bedienen können. Für alle würde ich es eher nicht einbauen. Trotzdem danke fürs Teilen!
