### ISSUE TITLE
Kommentarlinks laufen ins Verborgene

### ISSUE THREAD

**Issue by Harry-von-Borstel** [kre8tiv/urwahl3000#31]
Seit der Einfürung von Tabs für den Bereich unter den Artikeln (Verwandte Artikel / Kommentar verfassen / x Kommentare) funktionieren die Links zu den Kommentaren nicht mehr gut. Beispiel:
http://www.gruene-wandsbek.de/gruenschnack/impressum/comment-page-1/#comment-576

Den eigentlichen Kommentar sieht man hier nicht, da der Tab "2 Kommentare" nicht aktiv ist. Das ist für User nicht so toll, zumal diese Links im Widget "Neueste Kommentare" verwendet werden.

Eine mögliche Lösung wäre, den "x Kommentare" Tab als ersten Tab anzuzeigen, sobald ein Kommentar verfügbar ist.

**Comment by modulbuero** [comment]
Absolut, guter Hinweis. Ich habe die Tabs jetzt umgedreht, sodass die Kommentare auf 1, das Formular auf 2 und die Related Posts auf 3 sind. Damit sollte das Problem behoben sein.

**Comment by modulbuero** [comment]
Hallo Harry,

dann mach ruhig mal das Update auf die 2.1.18 – ich gehe davon aus, dass dir dann ohnehin die 2.2.0 ausgespielt wird. Ein Update geht immer nur auf die aktuellste Version.

Viele Grüße,
Christian
