### ISSUE TITLE
Termin Widget - Mehrtägige Termine werden nach Start nicht mehr angezeigt

### ISSUE THREAD

**Issue by pabloguerrez** [kre8tiv/urwahl3000#34]
Hallo zusammen,
Mehrtägige Termine werden im Widget nach Start nicht mehr angezeigt. Es wäre schön, wenn die Termine erst ausgeblendet werden wenn sie vorüber sind. Beispielnutzung: Aktuelles Volksbegehren in Bayern vom 31.01. bis 13.02.
Liebe Grüße!

**Comment by modulbuero** [comment]
Hallo Pablo,

danke dir für die Anregung. Das ist leider nicht ganz so einfach, da das zweite Datum ja nicht vorhanden sein muss, sondern nur kann. Wir müssten also beim Speichern des Termins prüfen, ob es ein "bis"-Datum gibt und dann dieses oder im anderen Fall das "von"-Datum für die Sortierung speichern. Das könnten wir zwar einbinden, müssten dann aber von euch verlangen, jeden Termin neu zu speichern. Um das zu verhindern, müssten wir quasi noch ein Update-Script schreiben. 

Ich nehme die Anregung also mal auf meine Liste, kann aber wegen unserer hohen Auslastung derzeit nicht versprechen, wann ich dazu kommen könnte. Alternativ könntet ihr natürlich so eine Änderung bei uns einkaufen, dann würden wir den Zeitplan deutlich ändern können. Aber das möchten und können wir natürlich nicht von euch verlangen.

Viele Grüße,
Christian
