### ISSUE TITLE
Teilen individualisieren

### ISSUE THREAD

**Issue by webmicha** [kre8tiv/urwahl3000#35]
Die teilen-Buttons sind ja fest verankert in content-single.php. Soweit ich das sehe, lässt sich das nicht grundsätzlich ausschalten, auch nicht in den WP Settings, oder? 

Ich würde lieber den Shariff Wrapper nutzen, der ist auch Datenschutzkonform und individualisierbar.

![fireshot pro screen capture 004 - kommunalwahl 2019 - bug durmersheimbug durmersheim - bug-durmersheim_de_2019_01_18_kommunalwahl-2019](https://user-images.githubusercontent.com/11209551/53598388-e38f3780-3ba4-11e9-81e6-4cd3e2702e01.png)

**Comment by modulbuero** [comment]
Hallo @webmicha,

die Teilen-Buttons sind auch in unserer Einbindung mit dem Datenschutz konform, da es sich nur um gestaltete Links handelt. Solltet ihr dennoch die Buttons ausschalten wollen, gibt es dafür einen Filter (siehe https://developer.wordpress.org/reference/functions/add_filter/) namens 'kr8_contentsingle_share'. Ihr müsstet also nur in ein Plugin oder die functions.php eures Themes folgenden Code einbauen:

add_filter('kr8_contentsingle_share', '__return_false');

Viele Grüße,
Christian

**Comment by webmicha** [comment]
Danke für die Info, hab die functions.php im Childtheme angepasst, das funktioniert :)

Eure Einbindung ist prinzipiell ok, nur deckt es halt keine Messenger ab. 
Der Shariff Wrapper ist da flexibler (kann sich ja auch mal was ändern) ohne den Code anfassen zu müssen.

**Comment by modulbuero** [comment]
> Danke für die Info, hab die functions.php im Childtheme angepasst, das funktioniert :)

Prima, freut mich.

> Eure Einbindung ist prinzipiell ok, nur deckt es halt keine Messenger ab.
> Der Shariff Wrapper ist da flexibler (kann sich ja auch mal was ändern) ohne den Code anfassen zu müssen.

Ja, da gebe ich dir recht, der Shariff ist in der Tat flexibler und leistungsfähiger. Aber so klappt es ja auch problemlos, ihn einzusetzen.
