### ISSUE TITLE
awesomefont outdated 

### ISSUE THREAD

**Issue by webmicha** [kre8tiv/urwahl3000#36]
Aktuell ist awesomefont 4.3 integriert. Da fehlen einige Icons aktueller Dienste, zB Messenger wie Telegram.
Mit Version 5.x haben sich die CSS Klassen geändert, man kann kann also "font-awesome.min.css" nicht einfach austauschen.

Es wäre schön das Theme und das Socialmedia Widget entsprechend anzupassen :)

**Comment by modulbuero** [comment]
@webmicha Ja, wir setzen die neue auch schon in einigen anderen Projekten ein. Leider ist das, wie du auch schon sagst, kein einfacher 1-zu-1-Tausch. Daher kann ich dir im Moment nicht sagen, wann wir dazu kämen. Wenn du selbst aktiv werden willst, kann du gerne einen Pull-Request stellen.
Viele Grüße,
Christian
