### ISSUE TITLE
Checkbox der cookie policy ist nicht richtig ausgerichtet

### ISSUE THREAD

**Issue by schiessle** [kre8tiv/urwahl3000#37]
So sieht die Eingabemaske für Kommentare bei us momentan aus:

![image](https://user-images.githubusercontent.com/1589737/54534729-48aca080-498d-11e9-80de-3ca52399c758.png)

Man beachte die Checkbox und das entsprechende Label "Meinen Namen, E-Mail und Website in diesem Browser speichern, bis ich wieder kommentiere." welches sehr unschön ausgerichtet ist.

Ein weitere Punkt, der Datenschutz Link zeigt hart auf `/datenschutz` in Wordpress kann man eine Datenschutz-Seite frei definieren (Einstellungen -> Datenschutz). Es wäre schön, wenn das Theme die Einstellung auslesen und die entsprechende Seite verwenden würde.

**Comment by modulbuero** [comment]
In v2.3.2 behoben, danke fürs Melden!
