### ISSUE TITLE
Keine Lizenzangabe

### ISSUE THREAD

**Issue by marians** [kre8tiv/urwahl3000#4]
Leider finde ich keine Lizenzangabe im Repository. Es wäre schön, wenn dadurch ermutigt werden könnte, den vorhandenen Code weiter zu verwenden. Ich denke gerade über eine Portierung in andere Template-Sprachen nach.

MIT oder Apache 2 wären sehr unkompliziert. Gerne auch Creative Commons mit Namensnennung (CC-BY).

Vielen Dank!

**Comment by marians** [comment]
@modulbuero Habt Ihr / hast Du mal darüber nachgedacht, dem Repository eine Lizenz zu geben?

**Comment by modulbuero** [comment]
Ja, haben wir. Wir wollen auf eine CC-NC-SA, haben aber noch GPL-lizenzierte Codes drin. Sobald wir wieder etwas mehr Luft im Büro haben, werden wir uns das wieder ansehen.

**Comment by schiessle** [comment]
Ich würde davon abraten eine CC-NC-SA zu verwenden. Aus mehreren Gründen. Generell sind die CC Lizenzen in erster Linie für Werke (Texte, Musik, Filme,...) konzipiert und daher vom Lizenztext auch darauf zugeschnitten. CC ist daher perfekt für den Content des Blogs geeignet, nicht aber zwangsweise für das Theme (Quellcode) 

Ein weitere Punkt, speziell CC-NC-BY wäre nicht mehr Freie Software, da die Kommerzielle Nutzung ausgeschlossen wäre. "Kommerziell" ist auch sehr wage und schwer zu definieren wo das anfängt und wo es aufhört.

**Comment by modulbuero** [comment]
@schiessle Danke für deinen Input. Kannst du den ersten Punkt etwas weiter begründen? 

Der zweite Punkt wäre für uns in der Tat gar nicht so schwierig zu sehen. Kommerzieller Einsatz heißt für uns, wenn mit dem Theme unmittelbar Geld verdient wird. Es geht dabei also nicht um Dienstleistungen rund um das Theme (Debugging, Features, etc.) oder um Beipacken des Themes zu normal bepreistem Hosting. 

Vielmehr haben wir uns zum Beispiel an den KollegInnen von GreenQ gestört, die das kostenlose Theme Urwahl3000 ganz eindeutig in einem Paketangebot für Internetseiten verwenden, das über den normalen Hostingpreis hinaus geht.

Sowas konterkariert das, was Ben Jopen und jetzt auch wir mit dem Theme beabsichtigen und ist einfach unfair. Und dagegen würden wir uns gerne in Zukunft wehren können. Daher war die Überlegung, das über eine CC-NC-BY zu machen. 

Falls du dazu andere Ideen oder Vorschläge hast, sind wir natürlich offen dafür.

**Comment by schiessle** [comment]
@modulbuero gerne, Wenn man beide Lizenzen liest merkt man an verschiedenen Stellen das sie auf verschiedene Werke zugeschnitten sind. Zum Beispiel wird bei Softwarelizenzen explizit zwischen Quellcode, ausführbarem code, usw unterschieden. Ein Text kennt das nicht, das Werk ist gleichzeitig auch der "Quelltext".

Siehe dazu auch: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

> Der zweite Punkt wäre für uns in der Tat gar nicht so schwierig zu sehen. Kommerzieller Einsatz heißt für uns, wenn mit dem Theme unmittelbar Geld verdient wird. 

Letztlich ist bindend, was in der Lizenz steht. Ihr seit ja auch nicht der alleinige Urheber da ihr pull requests von externen Leuten akzeptiert. Jeder von denen hält Rechte an dem Werk und jeder kann die Lizenz durchsetzen. Wenn dann nicht klar ist was "non-commercial" bedeutet und jemand zum Beispiel der Ansicht ist, dass das Theme schon kommerziell verwendet wird wenn auf dem Blog eine kostenpflichtige Veranstaltung beworben wird kann das schnell zu Problemen führen.

> Vielmehr haben wir uns zum Beispiel an den KollegInnen von GreenQ gestört, die das kostenlose Theme Urwahl3000 ganz eindeutig in einem Paketangebot für Internetseiten verwenden, das über den normalen Hostingpreis hinaus geht.

Ich kann das verstehen. Letztlich ist das aber eine Kerneigenschaft von Freier Software. Jeder kann die Software beliebig verwenden, anpassen und weitergeben. Ihr profitiert ja auch selber davon. Sowohl das Wordpress Freie Software ist als auch das ihr andere freie Komponenten in eurem Theme verwendet habt.

Interessant in dem Zusammenhang ist auch was Wordpress selber dazu schreibt. Zumindest der PHP Teil gilt in der Regel als abgeleitetes Werk von Wordpress und muss damit auch unter der GNU GPL stehen:

https://developer.wordpress.org/themes/getting-started/wordpress-licensing-the-gpl/

Die Kernidee von Freier Software ist das es für Unabhängigkeit und Chancengleichheit sorgt.  Dadurch das Wordpress und die externen Komponenten die ihr in eurem Theme verwendet habt Freie Software sind konntet ihr Urwahl3000 erstellen und viele andere tolle Seiten, Themes, etc und damit auch Geld verdienen. Warum sollten andere nicht das gleiche Recht haben.

Letztlich glaube ich wird es schwer eine andere Lizenz zu nehmen. Wegen der Wordpress Lizenz, der Lizenz externer Quellen die ihr verwendet und jedem einzelnen Pull Request den ihr bisher akzeptiert habt und der jedesmal ein Stückchen Code unter der GPL hinzugefügt hat. Wie oben versucht zu erklären glaube ich auch, dass ihr euch damit mehr schadet als nutzt. Im worst-case wird jemand die letzte freie Version forken und auf dessen Basis zusammen mit der Community weiter arbeiten. Aber auch wenn ihr euch von den Argumenten nicht abhalten lässt ist es best-practice die Lizenz im Repository entsprechend anzugeben. Das ist momentan die GNU GPL. Solltet ihr irgendwann eine andere Lizenz haben könnt ihr die Angabe problemlos anpassen.

**Comment by modulbuero** [comment]
@schiessle Danke für die ausführliche Rückmeldung, die ich sehr gut verstehen kann. Wir werden das hier nochmal intern diskutieren, aber ich gehe im Moment davon aus, dass wir den Empfehlungen so folgen werden.

**Comment by modulbuero** [comment]
Wir haben jetzt die Lizenz als GNU GPL 3.0 eingestellt, danke für all euren Input!
