### ISSUE TITLE
Blocksatz deaktivierbar?

### ISSUE THREAD

**Issue by UweKeim** [kre8tiv/urwahl3000#40]
Auf mobilen Browsern, speziell auf Android/Chrome, schaut Blocksatz eher mau aus.

```css
text-align: justify;
```

**Frage:**

Kann ich das selbst geschickt deaktivieren, oder muss ich direkt im "style.css"-Quelltext dafür Hand anlegen?

**Comment by UweKeim** [comment]
Ich habe mir jetzt erst mal mit einem eigenen CSS via [Simple Custom CSS](https://wordpress.org/plugins/simple-custom-css/) beholfen:

```css
article.post {
  text-align: left !important;
}
```

Das funktioniert, ggf. ist das, trotz dem hässlichen `!important` schon eine dauerhafte Lösung.

**Comment by modulbuero** [comment]
Hallo @UweKeim ,

ja, genau das hätte ich jetzt tatsächlich auch empfohlen. Das !important tut etwas im Auge weh, aber schadet ja nicht wirklich ;-)

Viele Grüße,
Christian
