### ISSUE TITLE
Wordpress aus dem Herz-Symbol eine SVG-Datei die extern nachlaedt

### ISSUE THREAD

**Issue by ymybe** [kre8tiv/urwahl3000#45]
Im footer.php macht Wordpress im Copyright aus dem Symbol:

❤
Diese SVG-Grafik 

> `<img draggable="false" class="emoji" alt="❤" src="https://s.w.org/images/core/emoji/11.2.0/svg/2764.svg" style="display: inline-block; min-width: 20px !important; min-height: 20px !important; border: 1px solid rgba(0, 0, 0, 0.1) !important; background: rgb(255, 255, 255) url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAAAAACoWZBhAAAABGdBTUEAALGPC/xhBQAAAAJiS0dEAP+Hj8y/AAAAB3RJTUUH3wwIAAgyL/YaPAAAACJJREFUCFtjfMbOAAQ/gZiFnQPEBAEmGIMIJgtIL8QEgtoAIn4D/96X1KAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTUtMTItMDhUMDA6MDg6NTArMDM6MDAasuuJAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE1LTEyLTA4VDAwOjA4OjUwKzAzOjAwa+9TNQAAAABJRU5ErkJggg==&quot;) repeat scroll 0% 0% !important;">`

Um das Laden von externen Inhalten der Wordpress-Server zu verhindern schlage ich vor:

&amp;hearts;  ( &amp;amp; zur Darstellung verwendet) => &hearts;

im Quelltext zu verwenden.

**Comment by modulbuero** [comment]
Vielen Dank für den Hinweis! Ich habe die emoji.js, die die Ersetzung vornimmt, einfach komplett entfernt. Die sollte man ohnehin nicht benutzen. Closed in v.2.3.7.
