### ISSUE TITLE
Hamburger-Menü und die Suche funktionieren in der mobilen Ansicht nicht

### ISSUE THREAD

**Issue by modulbuero** [kre8tiv/urwahl3000#46]
Hi, hängt vielleicht damit zusammen: Das Hamburger-Menü und die Suche funktionieren in der mobilen Ansicht nicht, d.h. das Seitenmenu ist nicht erreichbar.

_Originally posted by @dasaweb in https://github.com/kre8tiv/urwahl3000/issues/26#issuecomment-489347462_

**Comment by modulbuero** [comment]
Hey @dasaweb, 

ich habe daraus mal einen neuen Issue gemacht, da das leider nicht zusammen hängt. Auch kann ich das Problem auf meiner Testumgebung nicht nachvollziehen. Könntest du mir einen Link zu einer Seite schicken, wo das Problem konkret auftritt?

Viele Grüße,
Christian

**Comment by dasaweb** [comment]
Hi @modulbuero,

danke für's Erstellen des neuen Issues.

Ich hab das gesehen direkt auf https://www.urwahl3000.de, und zwar mit dem mobilen Chrome 74 unter Android 9 auf einem Oneplus 5T. Wobei die Details glaube ich nicht so wichtig sind, ich kann das Problem auch unter Chrome 73 und 74 auf Win10 reproduzieren, wenn ich in der Developer Console auf mobile Ansicht wechsle und versuche, auf das Hamburger Menu zu klicken. In der URL springt er auf den Anker "#menu", sonst passiert aber nichts. Auch der Firefox 66 verhält sich so. Die Menupunkte "Dokumentation", "Demo", "Download" und "Blum-O-Matic" sind da auf der Seite einfach nicht zu finden.

Wo sollten die in der mobilen Ansicht denn auftauchen?

Grüße!
Daniel

**Comment by modulbuero** [comment]
Hi @dasaweb,

oh, wie peinlich :-) Hier hatte sich aber nur das Minifizierungs-Plugin BWP Minify aufgehangen. Das habe ich nun deaktiviert und jetzt ist das Menü (samt den von dir genannten Punkten) wieder erreichbar. Tritt der Fehler noch irgendwo anders auf?

Viele Grüße,
Christian

**Comment by dasaweb** [comment]
Das ist genau gar nicht peinlich, sowas ist immer drin ;-) Gut, dass es wieder läuft. Woanders habe ich den Fehler nicht gesehen, passt also.

Das Plugin kannte ich gar nicht, werde ich mir mal ansehen, macht wohl Sinn, das einzusetzen. Daher schon mal vorsichtig nachgefragt: Was meinst du mit "hat sich aufgehangen" bei einem WP-Plugin? Wenn du es jetzt deaktiviert hast bedeutet das, dass es doch nicht so gut out of the box funktioniert?

Grüße!
Daniel

**Comment by modulbuero** [comment]
Das ist ganz einfach: Das Plugin minifizert den CSS- und JS-Code, entfernt also Leerzeichen und Absätze sowie Kommentare. Wenn jetzt im JavaScript Kommentare einfach nur mit // vor der Zeile ausgeklammert werden, dann wird diese Kommentierung nicht mehr richtig geschlossen, da der Absatz fehlt, und alles danach geht den Bach runter. Man kann dann entweder den Fehler suchen und auf richtige Kommentierung mit /* */ umstellen, oder man deaktiviert das Plugin einfach erstmal, weil man keine Zeit hat :-D

**Comment by dasaweb** [comment]
Verstehe, danke für die Aufklärung. Ehrlich gesagt kommentiere ich einzelne Zeilen auch gerne so aus... Das Plugin könnte das ja aber auch abfangen und ordentlich parsen, wobei mir klar ist, dass das im Einzelfall gar nicht so trivial ist. Aber die JavaScript Engine schafft das ja auch.

Egal, jetzt weiß ich, wo das Problem mit dem Plugin liegen kann, danke. 

Grüße und frohes Schaffen,
Daniel
