### ISSUE TITLE
"Startseite mit drei Kacheln" Template und Sticky post.

### ISSUE THREAD

**Issue by schiessle** [kre8tiv/urwahl3000#47]
Wir verwenden als Startseite das Template "Startseite mit drei Kacheln (Sticky Posts)"

Im normalen Betrieb sieht das auch super aus. Wenn jedoch ein Blog als "Auf der Startseite halten" markiert wurde sieht die Startseite so aus:

![image](https://user-images.githubusercontent.com/1589737/57233856-bd13cf80-701f-11e9-8f58-2e579ac72cb2.png)

Der Beitrag "Kreis-Seniorenrätin Waltraud Bühl am Runden Tisch – Montag, 6. Mai 2019 um 20 Uhr im Rössle" wurde als "Auf der Startseite halten" markiert. Wie man sieht gibt es rechts davon jetzt einen freien Bereich. Eigentlich würde ich erwarten das dort die nächsten zwei Beiträge stehen.

Wenn ich den Beitrag nicht mehr als "Auf der Startseite halten" markiere sieht alles wieder gut aus:

![image](https://user-images.githubusercontent.com/1589737/57234048-2d225580-7020-11e9-89c7-cc9c9809e46c.png)

Ist das ein Fehler im Theme oder ist es gewollt das der als "Auf der Startseite halten" markierte Beitrag alleine oben steht um ihn besser hervorzuheben? Dann würde ich aber erwarten das er die volle Breite nutzt, damit es nicht so aussieht als ob rechts etwas fehlen würde.

**Comment by modulbuero** [comment]
@schiessle Vielen Dank für den Fehlerbericht, das war mir tatsächlich bisher nicht aufgefallen. Ich vermute nicht, dass das ein erwünschtes Verhalten war, sondern eher dass die Programmierung hier nicht ganz sauber aufgesetzt war. 

Ich habe das Problem jetzt gefixed und gehe wie folgt vor:
1. Wir fragen die Sticky Posts ("Auf der Startseite halten") ab und nehmen bis zu 3 Stück mit
2. Wenn weniger als 3 Sticky Posts vorliegen, füllen wir mit entsprechend vielen normalen Beiträgen chronologisch absteigend sortiert auf
3. Wie gehabt werden die Sticky Posts dann unten aus der normalen Darstellung entfernt

Bitte prüf' mal, ob das für euch die gewünschte Wirkung zeigt und gib mir etwaige Rückmeldungen einfach hier durch.

**Comment by schiessle** [comment]
Vielen Dank für die schnelle Reaktion. Es sieht schon viel besser aus, habe aber noch einen kleinen Fehler entdeckt. Das "Sticky Post" ist in meinem Fall der aktuellste Beitrag. Er wird jetzt zweimal angezeigt:

![image](https://user-images.githubusercontent.com/1589737/57288720-50014800-70ba-11e9-81d4-e46d58a71c1c.png)

**Comment by modulbuero** [comment]
Blöder Fehler meinerseits; ich hatte vergessen, die Sticky-Posts in der Abfrage unter 2. wieder auszuschließen. Ist behoben :-D
