### ISSUE TITLE
tartget in `theme-sidebars.php` mit php code

### ISSUE THREAD

**Issue by cabisa** [kre8tiv/urwahl3000#48]
In der gerenderten Seite erscheint bei den Sozialen Medien `target="<?php echo $tab; ?>"`.

Lösung: Ersetze `<?php echo $tab; ?>`mit `'.$tab.'`

**Comment by cabisa** [comment]
https://github.com/cabisa/urwahl3000/pull/1

**Comment by modulbuero** [comment]
Vielen Dank, ist nun integriert.
