### ISSUE TITLE
Titelbilder werden automatisch zentriert gecropped - Option als Backend

### ISSUE THREAD

**Issue by chrkrrr** [kre8tiv/urwahl3000#51]
Hallo!

Das Titelbild eines Beitrags wird immer hart zentriert gecropped. Ich würde mir wünschen, dass zumindest grundsätzlich die Einstellung über das Backend konfigurierbar ist.

Dazu muss ja nur die Option aus der theme-functions.php für das
add_image_size( 'titelbild', 850, 450, true ); 
ins Backend. Optionen gibts ja als Parameter ausreichend:

    If false (default), images will be scaled, not cropped.
    If an array in the form of array( x_crop_position, y_crop_position ):
        x_crop_position accepts ‘left’ ‘center’, or ‘right’.
        y_crop_position accepts ‘top’, ‘center’, or ‘bottom’. Images will be cropped to the specified dimensions within the defined crop area.
    If true, images will be cropped to the specified dimensions using center positions.
https://developer.wordpress.org/reference/functions/add_image_size/

Was mir noch unklar ist, ist ob es einen sinnvollen Case gibt, in dem man die Option pro Beitrag definieren möchte. Das ist aber wohl eher selten der Fall...

Vg,

Christoph

**Comment by modulbuero** [comment]
Hallo Christoph,

danke für deine Nachfrage. Eine Konfiguration über das Backend würde mir jetzt zu aufwändig erscheinen, könntest du stattdessen auch mit einer [Filterung über PHP](https://developer.wordpress.org/reference/functions/add_filter/) leben? Diese könntest du einfach in einem kleinen Plugin oder der functions.php des Child-Themes einbauen.

Viele Grüße,
Christian

**Comment by chrkrrr** [comment]
Hi Christian,

wenn es dir aktuell nur zu aufwendig ist und grundsätzlich aus deiner Sicht nichts gegen eine Option steht, schick dir heute Abend einen Pullrequest und baue es eben schnell selbst ein.

Vg,

Christoph

**Comment by modulbuero** [comment]
Hi,

das ist natürlich immer eine Option. Ich würde nur gerne vorher kurz die Details wissen, wo und in welcher Form du das einbauen möchtest, wenn das für dich ok ist. Natürlich kannst du auch direkt einen PR schicken, aber eventuell müsste ich dann um eine Korrektur bitten. Daher wäre ein kurzer Austausch vorher vielleicht einfacher. 

Viele Grüße,
Christian

**Comment by chrkrrr** [comment]
Ich denke das sinnvollste wäre eine Punkt im Customizer zu ergänzen und dann eine Dropdownbox zur Auswahl...

**Comment by modulbuero** [comment]
Und in der Dropdownbox wären dann alle Werte je Länge und Breite kombiniert untereinander mit center x center als Default?

**Comment by chrkrrr** [comment]
Ne, ich würde die Einträge wie folgt benennen:
1.) Scaled / Resize
2.) Cropped (center)
3.) Cropped individual-> Zwei Felder für x und y

**Comment by modulbuero** [comment]
Mh, das ist mir ehrlich gesagt etwas schwer verständlich benannt für eher unbedarfte NutzerInnen. Dann verstehen es doch wieder nur Leute mit Entwicklungshintergrund und dann würde der Filter auch ausreichen. Wenn du da vielleicht nochmal überlegen könntest?

**Comment by chrkrrr** [comment]
klar, hast Recht. Ich neige zum "overengineering"

**Comment by modulbuero** [comment]
Gar kein Problem, deshalb tauschen wir uns ja aus. Willst du den Filter einsetzen und nen PR schicken oder soll ich das (morgen oder so) machen?

**Comment by chrkrrr** [comment]
Mach du ruhig ;)

**Comment by modulbuero** [comment]
So, ist nun nachgerüstet. Da es sich gleich um eine Reihe Definitionen handelte, habe ich nicht einzelne Filter eingesetzt, sondern einen drum herum. Oder wie's in der Commit-Beschreibung heißt:

> Just add_filter on 'kr8_thumbnail_default' to __return_false, then redefine thumbnail sizes under the exact same name in your child-theme or plugin.
