### ISSUE TITLE
Problem überhalb des Headermenüs

### ISSUE THREAD

**Issue by stefanchristoph** [kre8tiv/urwahl3000#6]
Ich habe bei dem Template leider ein Problem, dass bei vielen Seiten, Artikeln usw. überhalb des Headermenüs ein Textschnipsel mit abschließender Klammer angezeigt wird wie hier beispielsweise: http://www.gruene-regensburg.de/wahlen-2018/

Überhalb des Top-Menüs steht da `2018"> `
Ich bin jetzt allerdings nicht sicher ob das ein Problem innerhalb des Templates ist, es an einem Plugin liegt, oder ich in einem eigenen Fix was falsch gemacht habe.

Danke schon einmal für die Hilfe!

**Comment by modulbuero** [comment]
Mein Verdacht ist, dass das aus den OpenGraph-Tags kommt:

`

  | <meta itemprop="og:site_name" content="Stadtverband Regensburg">
  | <meta itemprop="og:title" content="Wahlen <span class="numbers">2018</span>">
  | <meta itemprop="og:type" content="article">
  | <meta itemprop="og:url" content="http://www.gruene-regensburg.de/wahlen-2018/">
  | <meta property="og:description" content="Wahlen 2018 \| Grüne&nbsp;"/>
`

Das <span> um die 2018 im og:title dürfte da nicht stehen. Probier's mal in der Richtung und berichte gern hier, ob das geklappt hat.

**Comment by stefanchristoph** [comment]
Ha, ich hätte auch früher draufkommen können, aber ich habe daraufhin noch einmal die Plugins durchgetestet und es ist anscheinend das "wp-Typography"-Plugin, das dann eingreift, wenn es Zahlen, Anführungszeichen o.ä. gibt um die typografisch richtig zu formatieren.

Also habe das Problem und schaue mal, ob ich es innerhalb der Plugin-Einstellungen lösen kann; deaktivieren behebt das Problem aber auf jeden Fall.

**Comment by modulbuero** [comment]
Perfekt, danke für die rasche Rückmeldung!

**Comment by stefanchristoph** [comment]
Einfach den `meta`-Tag ausschließen funktioniert aber leider schonmal nicht.

**Comment by modulbuero** [comment]
Interessant, gehts vielleicht auf den `<head>` komplett?

**Comment by stefanchristoph** [comment]
Auch nicht, der ist sowieso von vornherein ausgeschlossen. Ich werde bei Gelegenheit mal noch rumprobieren aber deaktiviere es jetzt vorerst einmal.

**Comment by marians** [comment]
PR https://github.com/kre8tiv/urwahl3000/pull/9 enthält einen Fix.

**Comment by modulbuero** [comment]
Fix aus PR #9 kommt dann morgen. Danke für alle Unterstützung.
