### ISSUE TITLE
SubMenu > 2 levels

### ISSUE THREAD

**Issue by Doogiemuc** [kre8tiv/urwahl3000#61]
Hallo kre8tiv Team!
Danke für euer tolles Urwahl3000 Theme. Sieht echt gut aus und ist ganz gut konfigurierbar. Wir nutzen es für unsere gruene-dachau.de Seite.

Ich versuche gerade ein Untermenü mit mehr als 2 Ebenne zu gestalten. Ich habe bereits herausgefunden, dass das Menü in Theme / functions / theme-functions.php  auf 2 Ebenen beschränkt wird.

```
/*********************
MENUS & NAVIGATION
*********************/

// the main menu
function kr8_nav_main() {
	// display the wp3 menu if available
    wp_nav_menu(array(
    	'container' => false,                           // remove nav container	
    	'menu_class' => 'navigation clearfix',         // adding custom nav class
    	'theme_location' => 'nav-main',                 // where it's located in the theme
    	'before' => '',                                 // before the menu
        'after' => '',                                  // after the menu
        'link_before' => '',                            // before each link
        'link_after' => '',                             // after each link
        'depth' => 2,                                   // limit the depth of the nav    <==========
    	'fallback_cb' => 'kr8_main_nav_fallback'      // fallback function
	));
} /* end kr8 main nav */
```

Wenn ich jedoch den Parameter `depts` auf 3 ändere passt das CSS layout nicht mehr. Die Untermenüs auf dritter Ebene werden sofort überlappend angezeigt. Ohne :hover. Sieht nicht schön aus.

https://ibb.co/1LQf1R8

Gibt es vielleicht eine neuere Verison des Templates in der das geht?

**Comment by modulbuero** [comment]
Hallo Robert,

danke für deine Nachricht. Tatsächlich sind hier gleich mehrere Probleme zu erwarten:

1. Wie von dir angesprochen reicht das CSS nicht für mehr als 2 Ebenen aus. Hier kannst du gern einen Vorschlag machen, wie das aussehen könnte, und diesen als Pull-Request hier einstellen. Wobei ich mir selbst noch nicht so sicher bin, ob 3 Ebenen hier wirklich sinnvoll sind, aber das käme auf einen Versuch an.

2. Liegt die theme-functions.php ja innerhalb des zu updatenden Theme und darf/sollte deshalb nicht direkt bearbeitet werden. Hierfür müsste also ein Child-Theme erstellt werden – womit wir gleich zu 3. kommen:

3. Ist die function kr8_nav_main() nicht pluggable ausgeführt – du kannst sie also im Child-Theme nicht ohne weiteres überschreiben. Stattdessen müsste man also vermutlich mit einem Filter arbeiten. Dafür würde sich vermutlich wp_nav_menu_args anbieten. Oder aber wir ändern die function mit einem Update auf pluggable.

Das vielleicht mal als ein paar Anstöße. Hilft dir das in deinen Überlegungen schon einmal weiter?

Viele Grüße,
Christian

**Comment by Doogiemuc** [comment]
Hallo Christian!
Vielen herzlichen Dank für die schnelle Antwort. Ja auf genau diese Herausforderungen bin ich dann auch gestoßen. 

Wir haben jetzt letztenldich doch eine andere Lösung gefunden: Wir nutzen ein [Wordpress Tab Plugin](https://de.wordpress.org/plugins/tabs-responsive/). Damit haben wir die nötige dritte Unterebene.

**Comment by modulbuero** [comment]
Alles klar, danke für die Rückmeldung!
