### ISSUE TITLE
Wechsel der PHP-Version von 7.1 auf 7.2 oder 7.3...

### ISSUE THREAD

**Issue by NoDoubts** [kre8tiv/urwahl3000#62]
Nach dem Wechsel der PHP-Version ist leider kein Login ins BackEnd mehr möglich.

**Comment by modulbuero** [comment]
@NoDoubts kannst du mir einen Screenshot und ggf. Link zur Seite schicken?

**Comment by NoDoubts** [comment]
www.gruene-nauheim.de

![image](https://user-images.githubusercontent.com/31853204/74421884-082ffe00-4e4e-11ea-8206-a123b6150762.png)

**Comment by NoDoubts** [comment]
Bin auf 7.1 und aktualisiere gerade das Theme. Danach probiere ich es noch einmal.

**Comment by modulbuero** [comment]
@NoDoubts Das sollte auf jeden Fall helfen, denn den genannten Fehler kann ich in der aktuellen Version jedenfalls nicht finden.

**Comment by modulbuero** [comment]
Ahja, ich sehe gerade den Fehler – der wurde am 21 Feb 2016 behoben. Ein (dringend überfälliges) Update sollte euch also helfen ;-)

**Comment by NoDoubts** [comment]
Das closed kommt zu früh. Bei Umstellung wieder da.... Was soll ich noch updaten?

**Comment by NoDoubts** [comment]
OK, Fehler gefunden. Wir waren mit unserer Seite Frühstarter des Urwahl-Themas und wir hatten die Version von Benjamin Joppen noch drauf. Die endete aber bei 2.0.5. Wir hatten Anfangs Probleme mit Eurem Theme und hatten dann wohl übersehen, dass das alte ausgelaufen ist. Meistens sitzt der Fehler vor dem Kasten. Gruß, Marco

**Comment by modulbuero** [comment]
Alles klar, danke für die Info.
