### ISSUE TITLE
Layout der Newsliste der Startseite bei langen Kategorienamen

### ISSUE THREAD

**Issue by rittmeier** [kre8tiv/urwahl3000#63]
Hallo,
wenn wir bei Newsbeiträgen nur wenige Kategorien und Tags auswählen, dann wird eine News in der Übersicht wie folgt gerendert:
![grafik](https://user-images.githubusercontent.com/1170084/75048904-9436cb00-54c9-11ea-9e02-821747555424.png)

Wählen wir zu viele Kategorien oder Tags aus, dann springt der Text unter das Bild, was einen unschönen Weißraum erzeugt:
![grafik](https://user-images.githubusercontent.com/1170084/75048843-7c5f4700-54c9-11ea-81a3-0a86ab619bc6.png)
"Früher" war das meine ich kein Problem, weil wir beim Erstellen der News drauf geachtet haben, nicht zu viele Kategorien auszuwählen. Ich meine, dass im letzten Jahr dann irgendwann urwahl3000 so angepasst wurde, dass auch das Datum ausgegeben wird (was positiv ist!) und damit wurden auch viele bestehende News anders gerendert. Der Aufwand mehrere Jahre an bestehenden News redaktionell anzupassen wäre unangenehm hoch.

Ist es möglich, dass das CSS/Layout so angepasst wird, dass das Rendering auch bei langen Kategorien / Tags das Bild umfließt? Ungefährt wie in der folgenden Skizze:
![grafik](https://user-images.githubusercontent.com/1170084/75050099-a285e680-54cb-11ea-8fe4-2ab7dd03e9b9.png)

**Comment by modulbuero** [comment]
Hey @rittmeier, vielen Dank für den Hinweis – ich habe dazu eine Korrektur als v2.6.4 veröffentlicht. Schau bitte mal, ob das für dich klappt.

**Comment by rittmeier** [comment]
Danke, das löst die großen weißen Flächen erfolgreich auf!

Allerdings ist es in einem Detail noch nicht optimal / schlechter als vorher. Das habe ich in der Soll-Skizze aber leider auch nicht richtig dargestellt. Früher startete die Textvorschau des Newsbeitrags neben dem Bild, wenn genügend Platz vorhanden war. So wie man das in der allerersten Grafik dieses Tickets sieht. Ist es möglich, das man diese Eigenschaft trotzdem erhalten kann? 

Aktuell startet die Textvorschau immer unter dem Bild:
![grafik](https://user-images.githubusercontent.com/1170084/75156945-6e046b80-5713-11ea-8c66-8585555714f6.png)

**Comment by modulbuero** [comment]
Du hast völlig Recht, das hätte so nicht aussehen sollen. Ich habe die Darstellung nochmal angepasst in Version 2.6.5. Melde dich bitte dann nochmal, ob es für dich passt. Danke!

**Comment by rittmeier** [comment]
Erstmal danke für diese super schnellen Anpassungn! 💚 

Man könnte höchstens noch überlegen, ob das Datum immer als ein Block / nbsp dargestellt werden sollte, sodass es wenn als eine Einheit in die nächste Zeile rutscht und nicht nur teilweise.
![grafik](https://user-images.githubusercontent.com/1170084/75160567-8926a980-571a-11ea-8822-15ad2d5f8e9d.png)

**Comment by modulbuero** [comment]
Ja, auch das ist eine prima Idee. Ist nun in v2.6.6 eingebaut. Bitte prüfe mal, ob das für dich funktioniert.

**Comment by rittmeier** [comment]
Danke, perfekt!
