### ISSUE TITLE
Menü "Kopfleiste" in der Smartphone-Ansicht

### ISSUE THREAD

**Issue by rittmeier** [kre8tiv/urwahl3000#64]
Hallo,
wenn wir unsere Seite mit urwahl3000 vom Smartphone besuchen, dann wird das Menü "Kopfleiste" leider überhaupt nicht gerendert. Es wäre toll, wenn die Inhalte des Menüs auch auf dem Smartphone gerendert werden. Hinsichtlich des "wie" sind wir halbwegs offen. :-) Z.B. als zusätzliche Hauptkategorie des Hauptmenüs oder vor das Menü "Fußzeile", ...

**Comment by modulbuero** [comment]
Und auch hier: ich habe dazu eine Korrektur als v2.6.4 veröffentlicht. Schau bitte mal, ob das für dich klappt.
