### ISSUE TITLE
Plugin-Empfehlung Twitter-Tracker aktuallisieren

### ISSUE THREAD

**Issue by ibes** [kre8tiv/urwahl3000#65]
Hallo,

in der Dokumentation wird das Plugin https://wordpress.org/plugins/twitter-tracker/ empfohlen, und gesagt, das Theme ist darauf vorbereitet. 
Das Plugin wurde seit 7 Jahren nicht mehr aktuallisiert.
Ich würde empfehlen, diese Plugin-Empfehlung aus der Dokumentation zu nehmen und/oder ein anderes Plugin zu empfehlen. 

Beste Grüße

**Comment by modulbuero** [comment]
Guter Tipp, danke dir. Da wir im Moment auch kein besseres als Empfehlung haben, nehme ich den Hinweis erst einmal raus.
