### ISSUE TITLE
Anmerkung zu Logo-Einbindung

### ISSUE THREAD

**Issue by ibes** [kre8tiv/urwahl3000#66]
https://github.com/kre8tiv/urwahl3000/blob/e6c331aca43be393663acfde038cd5d85bfa4fca/header.php#L104

Nach meiner Vorstellung will an der verlinkten Stelle die Möglichkeit gegbeben werden, dass ein Logo in SVG oder PNG-Format einzubinden, wobei SVG bevorzugt wird. 

Ich glaube, dass es da einen kleinen Logik-Fehler gibt. 

Ich hab das nicht praktisch getestet sondern nur aus dem Code geschlossen. 

Wenn ich im Child-Theme an die notwendige Stelle ein .svg-Logo lege, sollte das verwendet werden statt die Dateien im Parent-Theme. 
Wenn ich allerdings ein .png-Logo ins Child-Theme lege, sollte weiterhin das .svg-Logo aus dem Parenttheme verwendet werden, da der Check garnicht dazu kommt zu prüfen, ob es im Child-Theme ein .png-Logo gibt. 

Ich stelle mir vor, dass die Idee des Codes diese Priorisierung ist:
- Child-SVG
- Child-PNG
- Parent-SVG
- Parent-PNG

Defacto müsste sie sein:
- Child-SVG
- Parent-SVG
- Parent-PNG

Wobei bei ordnungsgemäßer Verwendung des Parent-Themes (nichts verändern, nichts löschen) das Parent-PNG niemals in Betracht gezogen wird, weil immer das Parent-SVG vorhanden ist.

**Comment by modulbuero** [comment]
Gut gesehen, @ibes ! Ist nun im nächsten Update behoben…

**Comment by ibes** [comment]
Super :)
