### ISSUE TITLE
Feature Request: "Stadt"-Feld in Termin-Plugin optional machen

### ISSUE THREAD

**Issue by digicommons** [kre8tiv/urwahl3000#68]
Die in Urwahl3000 eingebaute Termin-Funktion hat eine ganze Reihe von (Vor-) Einstellungen, die die Erstellung von Wiederholungsterminen vereinfacht. Die **Option "Stadt"**, die sicher für die meisten (ländlichen) Kreisverbände praktisch ist, verfehlt aber bei Großstadt-KVen ihr Ziel. Da der Großteil von Veranstaltungen in der selben Stadt stattfindet, ist die Darstellung der Stadt im Termin-Widget **redundant**.
Einige Kreisverbände füllen im Feld "Stadt" als **Workaround** stattdessen die Uhrzeit aus (Abb. 1), was im Widget gut aussieht, aber im eigentlichen Termin eine unnötige Wiederholung ist (Abb. 2).

Eine mögliche Lösung wäre, im Widget eine weitere Einstellungsmöglichkeit anzubieten und den Usern zu überlassen, ob Stadt oder Uhrzeit die jeweils relevantere Information ist:
Im Widget anzeigen: [ ] Stadt [ ] Uhrzeit

Sollte dieses Feature nicht zu viel Aufwand bedeuten, würde ich mich über eine Übernahme in Urwahl3000 freuen.

Beste Grüße
Jakob

### Abb. 1:
![image](https://user-images.githubusercontent.com/43313518/77670527-9d163300-6f86-11ea-8808-21adc0c49ea3.png)

### Abb. 2:
![image](https://user-images.githubusercontent.com/43313518/77671003-41987500-6f87-11ea-89c1-6b7897cf4dab.png)

**Comment by modulbuero** [comment]
Hallo Jakob,

hierüber muss ich mal einen Moment nachdenken. Daher lasse ich das Ticket erstmal offen und melde mich wieder.

Viele Grüße,
Christian

**Comment by digicommons** [comment]
Alright, danke! Bei Nachfragen zu UI höre ich mich gerne noch unter anderen KVen um.

**Comment by digicommons** [comment]
Schließe Issue, da das Theme scheinbar nicht mehr weiterentwickelt wird. Dennoch vielen Dank für den Support während der aktiven Entwicklung!
