### ISSUE TITLE
Feature Request: Meta-Tag theme-color einsetzen

### ISSUE THREAD

**Issue by digicommons** [kre8tiv/urwahl3000#69]
Einige Browser, u.a. Chrome für Android, passen die Farbe ihrer UI entsprechend dem Meta-Tag theme-color [1] [2] an. Bei Urwahl3000 bietet sich an, den Farbton #0a321e bzw. #46962b als theme-color zu definieren.

Da ein nicht zu unterschätzender Anteil von Nutzer*innen Chrome für Android nutzt, wäre dieses Feature ein simpler Weg, um sich im Browser von anderen Angeboten abzuheben.

[1] https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color
[2] https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android

**Comment by modulbuero** [comment]
Na, das können wir doch gerne machen. Jedoch würde ich das helle Grün nehmen und habe das gerade so gepusht.

**Comment by digicommons** [comment]
Das ging ja schnell! Danke.
