### ISSUE TITLE
Git-Tags für die Releases

### ISSUE THREAD

**Issue by davidfuhr** [kre8tiv/urwahl3000#71]
Hallo,
es wäre toll, wenn ihr eure Releases in Git auch taggen würdet. Dann kann man den passenden Release einfacher auschecken!
Danke!

**Comment by modulbuero** [comment]
Hallo David,

das ist ein völlig berechtigter Wunsch. Wir nutzen die Github-eigene Desktop-App für macOS – und die unterstützt leider immer noch keine Tags (vgl. https://github.community/t5/How-to-use-Git-and-GitHub/Tags-in-GitHub-Desktop/td-p/9923). Ich werde mal schauen, ob wir eine Alternative finden, ohne immer übers Terminal zu gehen. Falls du einen Tipp hast, melde dich immer gerne.

Viele Grüße,
Christian

**Comment by larsschellhas** [comment]
Anscheinend ist das seit Mai nun auch möglich :)
https://github.blog/2020-05-12-create-and-push-tags-in-the-latest-github-desktop-2-5-release/

**Comment by modulbuero** [comment]
Ah, prima, danke für den Hinweis. Werden wir gleich einbauen…
