### ISSUE TITLE
Slider im Headbereich

### ISSUE THREAD

**Issue by aba0815** [kre8tiv/urwahl3000#75]
Hallo,

Feines Theme, danke für eure Arbeit. Eine Frage: Gibt es (und wenn ja: welche) eine Möglichkeit, anstelle des statischen Headerbildes einen Slider einzubinden?

Danke und viele Grüße
A.

**Comment by modulbuero** [comment]
Hallo,

vielen Dank. Leider ist mir nichts dergleichen bekannt, das würde nur über ziemlich weitgehende Änderungen funktionieren. Für einzelne Kund*innen könnten wir (oder andere Dienstleister) das ggf. als Auftragsarbeit machen, aber eine tragfähige Lösung für alle Nutzer*innen ist dann noch einmal deutlich mehr Aufwand.

Somit erstmal closed hier.

Viele Grüße,
Christian
