### ISSUE TITLE
Suchergebnisse rendern Seiten-Ergebnisse ungekürzt

### ISSUE THREAD

**Issue by rittmeier** [kre8tiv/urwahl3000#76]
Hallo,

wir konnten für zwei Installationen mit urwahl3000 nachvollziehen, das auf der Suchergebnisseite https://domain.tld/?s=klimaschutz Suchergebnisse die ein Beitrag sind gekürzt dargestellt werden, Suchergebnisse die eine Seite sind, werden allerdings ziemlich vollständig ausgegeben werden. Ist also eine Seite mit viel Inhalt Teil des Suchergebnisses, dann steht eben dieser viele Inhalt dann in den Suchergebnissen.

Soweit ich das einschätzen kann, ist das jeweilige Theme an dieser Stelle maßgeblich für die Frage, "wieviel" bzw "wie" gerendet wird. Besteht die Möglichkeit einer Anpassung, sodass Seiten-Suchergebnisse auch nur gekürzt in der Suchergebnisseite gerendert werden?

**Comment by modulbuero** [comment]
Hallo Florian,

vielen Dank für den Hinweis, das ist nun im Update auf 2.7.6 behoben.

Viele Grüße,
Christian

**Comment by rittmeier** [comment]
Die Seite wird jetzt zwar gekürzt ausgegeben, es gibt aber keine Möglichkeit auf die Seite selbst zu kommen. Die "Weiterlesen"-Schaltfläche fehlt, eine Verlinkung der Überschrift wie bei Beiträgen wäre auch nicht falsch.

**Comment by rittmeier** [comment]
Und falls das Hauptbild der Seite als Miniatur gerendert würde, wäre das auch visuell noch schöner. :-)

**Comment by modulbuero** [comment]
Ach, du hast ja völlig Recht – man sollte so eine Änderung nicht morgens früh machen, da ist das Hirn noch nicht wach genug :-D 

Ist jetzt in v2.7.7 behoben.

**Comment by rittmeier** [comment]
Jetzt sieht es im Suchergebnis toll aus und hat auch die Verlinkung. :-)

Allein, bei einem Teil der Seiten habe ich nun das Problem, dass ich auch wenn die Seite aus dem Menü aufrufe, nur die gekürzte Fassung bekomme. Bzw. wenn ich der Weiterlesn-Schaltfläche folge, bekomme ich wieder nur eine Kurzdarstellung.

**Comment by rittmeier** [comment]
Zu sehen auf https://www.padergrün.de/, einfach die Einträge im Menü "Standpunkte" durchgehen. Beim zweiten Eintrag ist es korrekt, beim Rest wird nun auch die Seite gekürzt.

**Comment by modulbuero** [comment]
Ich sehne das Wochenende herbei :-D 

Wieder ein Flüchtigkeitsfehler bei mir, ist nun behoben in v2.7.8

**Comment by rittmeier** [comment]
Passt nun, vielen Dank! :-)
