### ISSUE TITLE
Termin-Widget gibt Datum manchmal doppelt aus

### ISSUE THREAD

**Issue by rittmeier** [kre8tiv/urwahl3000#79]
Habe das Termin-Widget in die Widget-Spalte gelegt und drei Termine konfiguriert. Einer mit Startuhrzeit 00:00, einer mit Startuhrzeit 21:42 und einer mit Startuhrzeit 22:00. Jeweils mit drei unterschiedlichen Startdatums-Angaben in der Zukunft.

Der Termin mit Startuhrzeit 00:00 wird anders als die anderen beiden Termine ausgegeben. Das Datum wird in diesem Fall doppelt ausgegeben. Ferner wird der Wochentag in Englisch ausgegeben, obwohl die Wordpress-System-Einstellung auf Deutsch steht.

![grafik](https://user-images.githubusercontent.com/1170084/86404281-9860c980-bcaf-11ea-9747-0f53c56c1678.png)

Im HTML sieht das so aus:
![grafik](https://user-images.githubusercontent.com/1170084/86404498-06a58c00-bcb0-11ea-9bfb-1af0f9a1946f.png)

**Comment by modulbuero** [comment]
Danke dir, Florian. Ist nun im neuen Update v2.8.2 behoben.

Viele Grüße,
Christian
