### ISSUE TITLE
"Startseite mit drei Kacheln"-Template zeigt weitere Sticky Posts nicht

### ISSUE THREAD

**Issue by gumby-man** [kre8tiv/urwahl3000#80]
Dies ist sicherlich eine Fortsetzung von [#47](https://github.com/kre8tiv/urwahl3000/issues/47) ("'Startseite mit drei Kacheln' Template und Sticky post.").

Ja, natürlich sollen Sticky Posts, die als Kachel erscheinen, nicht nochmal darunter als Beitrag erscheinen. Dennoch dürfen meines Erachtens deswegen nicht der vierte, fünfte Sticky Post auch herausgefiltert werden. So ist es aber leider im Moment. Die fehlen dann völlig.

**Comment by modulbuero** [comment]
@gumby-man sehr guter Hinweis, vielen Dank. Habe ich gerade im neuen Plugin behoben.

**Comment by gumby-man** [comment]
Wow, superschnell, Danke. Leider ist so ein Beitrag dann zwar sichtbar, aber nicht „sticky“ oben, sondern ganz einfach in die zeitliche Reihenfolge der Beiträge einsortiert (nur halt mit der hübsch-mintgrünen Hintergrundfarbe zur Hervorhebung).

**Comment by modulbuero** [comment]
Auch das ein sehr berechtigter Hinweis :-) Kommt gleich in der v2.8.6
