### ISSUE TITLE
Fehler bei Anzeige von Beitragsbildern der zugeordneten Unterseiten

### ISSUE THREAD

**Issue by athomas5020** [kre8tiv/urwahl3000#81]
Hallo,

über den Tag [Unterseiten Personen='ja'] haben wir u.a. auf unserer Vorstandsseite (https://gruene-hilpoltstein.de/vorstand/) die Listendarstellungen der zugeordneten Unterseiten mit den Beitragsbildern im Bullaugen - Format seit längerem aktiviert. Leider wurde durch eins der letzten Updates auf das Theme oder Wordpress selbst die Darstellung fehlerhaft. Es wird bei allen Bildern der untere Teil einfach abgeschnitten. Da wir, wie gesagt, sehr viele Unterseiten mit Beitragsbildern in diesem Format verwenden, wäre ich über eine technische Lösung sehr dankbar. Es gibt einen sehr umständlichen Workaround, bei dem ich das Bild von Wordpress im Medienbereich komplett löschen und neu hochladen muss. Danach muss ich es pro Unterseite als Beitragsbild neu zuordnen. Das habe ich bereits einmal für alle ca. 30 Bilder und Seiten durchgeführt, leider scheint das Problem sich offensichtlich zu wiederholen, wenn eine Aktualisierung auf den Code durchgeführt wird. Vielen Dank für die Hilfe

**Comment by modulbuero** [comment]
Hallo,

ich würde hier auf zu kleine Bilder schon im Upload tippen. Denn wir laden eigentlich das "square" Bildformat, das wir selbst im Theme registrieren mit add_image_size( 'square', 400, 400, true ); – also 400 mal 400 Pixel und fest beschnitten. Wenn das Bild nun kleiner als die besagte Größe ist, schneidet WordPress nicht mehr daran herum und so ergibt sich die fehlerhafte Darstellung. Gut zu sehen ist das auch an dieser Datei-URL: https://gruene-hilpoltstein.de/wp-content/uploads/2020/01/Homepage_06-e1598967181896.jpg – hier ist am Ende gar kein Größenhinweis für die Beschneidung angefügt, der sonst da sein müsste.

Kannst du mal schauen, ob das schon euer Problem ist?

Viele Grüße,
Christian

**Comment by athomas5020** [comment]
Hallo Christian,

vielen Dank für deine schnelle Antwort. Es scheint als wenn alle Bilder auf die Höhe 212 px abgeschnitten wären, tatsächlich sind sie in der Mediathek aber alle in der Abmessung 850 x 450 px gespeichert. Wenn ich für obiges Beispiel das Foto neu in die Mediathek Hochlade (850x450) und ersetze, wird es auch wieder richtig angezeigt. Aber wie gesagt, leider ändert WP die Abmessung dann auf 212 px....die Frage ist nur wann und warum. Sorry, ich weis nicht wie ich es besser beschreiben kann.

Danke und Lg
Andre

**Comment by modulbuero** [comment]
Hallo Andre,

dann würde ich als nächstes tippen, dass sich ein Plugin einmischt – könntest du mir mal einen Screenshot eurer Plugin-Liste hier reinpacken?

Vielen Dank und viele Grüße,
Christian

**Comment by athomas5020** [comment]
Hi Christian,

Sehr gerne, hier die Auflistung:

**Comment by modulbuero** [comment]
Ich kann da leider nichts sehen – willst du es mir vielleicht kurz per Mail an cj@modulbuero.de schicken?

**Comment by athomas5020** [comment]
Hi Christian,

Sorry, hab es dir gerade nochmal direkt per E-Mail geschickt.

Danke und Vg
Andre

**Comment by modulbuero** [comment]
Danke dir – da sehe ich jetzt nur ein Plugin, das mit den Medien interagiert: „Add from Server“. Könntest du das bitte mal deaktivieren und schauen, ob das das Problem behebt?

**Comment by athomas5020** [comment]
Hi Christian,

Ist deaktiviert, leider noch das ursprüngliche Verhalten.

Vg Andre

**Comment by modulbuero** [comment]
**Kurz zur Doku für Mitlesende**
Wir bekommen den Fehler nicht reproduziert und nutzen jetzt für den Moment das folgende Plugin, um die Bilder neu zu beschneiden: https://wordpress.org/plugins/ajax-thumbnail-rebuild/. Sollte der Fehler nochmal auftreten, schauen wir wieder drauf.
