### ISSUE TITLE
Social Share Buttons aktualisieren

### ISSUE THREAD

**Issue by larsschellhas** [kre8tiv/urwahl3000#82]
Momentan werden nur noch Twitter, Facebook und E-Mail als Social Sharing Optionen angeboten.
![image](https://user-images.githubusercontent.com/14281234/91965881-656b9e00-ed11-11ea-863d-d2afd6d7967b.png)

Die aktuell wichtigsten sozialen Netzwerke (Instagram, TikTok, etc...) fehlen demnach  allerdings.
Insgesamt wäre es schön, wenn der Admin einstellen könnte, welche Buttons angezeigt werden sollen, bzw. diese ausblenden.

Eine Option wäre evtl. den Shariff Wrapper (https://de.wordpress.org/plugins/shariff/) als Recommended/Required Plugin direkt mit einzubinden, anstatt eine Theme-Interne Lösung zu haben.

**Comment by modulbuero** [comment]
Hallo Lars,

danke für den Einwurf. Ich tue mich zwar etwas schwer mit deiner Einschätzung der "wichtigsten sozialen Netzwerke" – was Reichweite zumindest im politischen Kontext angeht sehe ich da jedenfalls wenig Relevanz. Auf mobilen Endgeräten blenden wir übrigens noch Telegram und WhatsApp ein, die auf dem Desktop nur bedingt funktionieren. Aber trotzdem hast du natürlich Recht, dass unter Umständen weitere Buttons wünschenswert wären. 

Da ich aber diese 5 Dienste schon als recht umfassend ansehe und auch unsere unbedarften Nutzer*innen nicht überfordern möchte, würde ich es im Standard gerne dabei belassen.

Für die fortgeschrittenen Nutzer*innen gibt es ja die Möglichkeit, den Filter 'kr8_contentsingle_share' auf false zu setzen und dann mit dem Shariff oder anderen guten Möglichkeiten zu arbeiten.

Ich hoffe, das hilft dir schon weiter.

Viele Grüße,
Christian

**Comment by larsschellhas** [comment]
Hey Christian,

ich komme darauf, weil ich jetzt von mehreren Ortsverbänden gefragt wurde, wie sie in Urwahl3000 denn Instagramm einbinden können. Für Nutzer des Hostings beim "Grünen CMS" ist das bearbeiten des Filters auch nicht so einfach.
Hinsichtlich der politischen Relevanz von Sozialen Medien, denke ich, dass es ein großer Fehler wäre, Nutzer nicht da abzuholen, wo sie am aktivsten sind. Dazu hier nochmal aktuelle Nutzerzahlen:
![image](https://user-images.githubusercontent.com/14281234/91967978-47536d00-ed14-11ea-826c-4b43b873a661.png)

Viele Grüße
Lars

**Comment by modulbuero** [comment]
Mh, dann würde ich das mal in Punkte unterteilen:

- Links zum eigenen Profil einbinden ist mit Urwahl3000 ja schon möglich über das Widget "Social Media Links". Hier ist auch Instagram verfügbar, TikTok allerdings nicht. Haben TikTok-Profile denn eine externe URL?
- Das Verlinken von Beiträgen der eigenen Website mit Urwahl3000 ist m.E. zumindest bei Instagram gar nicht möglich. Das müsste also händisch passieren mit einem Vorschaubild und Link in der Bio. Für TikTok dürfte das ähnlich gelten, wobei hier ohnehin mehr mit an die Plattform angepassten Videos gearbeitet werden sollte.
