### ISSUE TITLE
Anzahl der Beiträge auf der Startseite

### ISSUE THREAD

**Issue by fmklug** [kre8tiv/urwahl3000#86]
Hallo,
aktuell wird die Vorgabe der anzuzeigenden Beiträge auf der Webseite nicht im Thema realisiert:

pullach-gruene.de

Das sind ca. 20 Beiträge...
was muss ich einstellen, dass nur ca. 6 Beiträge auf der Startseite angezeigt werden?

Viele Grüße

Fabian

**Comment by modulbuero** [comment]
Hallo Fabian,

das liegt daran, dass ihr so viele Beiträge mit "Auf der Startseite halten" markiert habt, du erkennst es an der hellgrünen Hinterlegung. Diese greift unser Theme allesamt auf, was zu der großen Zahl von Beiträgen führt. Ihr müsstet also einfach bei einigen Beiträgen diese Checkbox deaktivieren.

Viele Grüße,
Christian

**Comment by fmklug** [comment]
> Hallo Fabian,

> das liegt daran, dass ihr so viele Beiträge mit "Auf der Startseite halten" markiert habt, du erkennst es an der hellgrünen Hinterlegung. Diese greift unser Theme allesamt auf, was zu der großen Zahl von Beiträgen führt. Ihr müsstet also einfach bei einigen Beiträgen diese Checkbox deaktivieren.

Hallo Christian,
oh Mann, danke für den Hinweis, dass ich da nicht selbst draufgekommen bin...
Was ich nur nicht verstehe, wie das passieren konnte....
Ich habe die Artikel so nicht gekennzeichnet...
Das muss durch ein Plugin, eine Aktualisierung oder durch einen Mitarbeiter passiert sein, der diese Artikel entsprechend markiert hat.... Wüsste allerdings nicht, wer...?
Großes Rätselraten...

Viele Grüße

Fabian

**Comment by modulbuero** [comment]
> Was ich nur nicht verstehe, wie das passieren konnte....
> Ich habe die Artikel so nicht gekennzeichnet...
> Das muss durch ein Plugin, eine Aktualisierung oder durch einen Mitarbeiter passiert sein, der diese Artikel entsprechend markiert hat.... Wüsste allerdings nicht, wer...?
> Großes Rätselraten...

Dabei kann ich euch leider nicht helfen ;-)
